/* eslint-disable no-irregular-whitespace */
export const en = {
    home_title: "I am Rafael Angulo",
    home_subtitle: "Rafgui is my personal brand and represents",
    portfolio: "Portfolio",
    experience: "Experience",
    contact: "Contact",
    home: "Home",
    blog: "Blog",
    // Portfolio
    portfolio_title: "Portfolio",
    portfolio_description: "Welcome to my portfolio, where I invite you to explore the diverse range of projects and experiences that have shaped my professional journey.",
    tools_label: "Tools and Technologies",
    // Experience
    experience_title: "Experiencia",
    work_text: "Work",
    education_text: "Education",
    // Contact
    contact_title: "Rafael Angulo Ealo",
    contact_description: "You can find me on these platforms or send me an email. Let's talk!",
    //Blog
    blog_title: "Rafael's Website Blog",
    blog_filtering_by: "Filtering by",
    blog_filter_type_category: "category",
    blog_filter_type_year: "year",
    blog_filter_type_author: "author",
    blog_clear: "Clear",
    blog_clear_filter: "Clear filter",
    blog_no_posts_filter_prefix: "No posts match the filter",
    blog_no_posts_available: "No posts available at the moment.",
    blog_show_all: "Show all posts",
    //BlogSideBar
    blog_filter_posts: "Filter Posts",
    blog_categories: "Categories",
    blog_years: "Years",
    blog_written_by: "Written by",
    blog_no_categories: "No categories available",
    blog_no_years: "No years available",
    blog_no_authors: "No authors available",
    // BlogPostPage
    blog_post_not_found: "Post not found.",
    blog_load_fail: "Failed to load the post.",
    blog_oops_title: "Oops! Something went wrong.",
    blog_back_to_blog: "Back to Blog",
    blog_by: "By",
    blog_my_opinion: "My Opinion",
    blog_opinion_not_available: "Opinion not available.",
    blog_no_opinion_yet: "No opinion yet.",
    blog_comments: "Comments",
    blog_anonymous: "Anonymous",
    blog_be_first_comment: "Be the first to comment.",
    blog_your_opinion: "Your Opinion",
    blog_form_placeholder: "Write your opinion here...",
    blog_submit_error: "Error saving your opinion. Please try again.",
    blog_submit_saving: "Saving...",
    blog_submit_save: "Save Opinion",
    //LoginPage
    login_title: "Login",
    login_email: "Email",
    login_password: "Password",
    login_btn: "Login",
    login_forgot_password: "Forgot your password?",
    login_password_reset_sent: "Password reset email sent! Check your inbox.",
    login_email_required_for_reset: "Please enter your email address above.",
    login_password_reset_error: "Error sending reset email. Please try again.",
    //AdminPanel
    admin_title: "Admin Dashboard",
    admin_welcome: "Welcome",
    admin_logout: "Logout",
    admin_manage_blog: "Manage Blog",
    admin_manage_portfolio: "Manage Portfolio",
    admin_manage_experience: "Manage Experience",
    admin_back_to_dash: "Back to Dashboard",
    //AdminBlog
    admin_manage_blog: "Manage Blog",
    admin_create_post: "Create New Post",
    admin_edit_post: "Edit Post",
    admin_post_title: "Post Title",
    admin_post_author: "Author",
    admin_post_categories: "Categories (comma separated)",
    admin_post_categories_placeholder: "e.g., Tech, Dev, AI",
    admin_post_image: "Header Image",
    admin_post_short_desc: "Short Description (Preview)",
    admin_post_content: "Content (Markdown)",
    admin_post_opinion: "My Opinion (Markdown)",
    admin_post_comments: "Manage Comments",
    admin_post_comments_enable: "Enable visitor comments",
    admin_post_no_comments: "No comments on this post yet.",
    admin_post_delete_comment: "Delete this comment?",
    //AdminProfile
    admin_profile_title: "Edit Profile",
    admin_profile_wip: "Profile editing coming soon...",
    admin_profile_tooltip: "Edit Profile",
    admin_logout_tooltip: "Logout",
    admin_profile_display_name: "Display Name",
    admin_profile_photo_url: "Photo URL",
    admin_profile_update_profile: "Update Profile",
    admin_profile_email_address: "Email Address",
    admin_profile_new_email: "New Email",
    admin_profile_update_email: "Update Email",
    admin_profile_password: "Password",
    admin_profile_new_password: "New Password",
    admin_profile_update_password: "Update Password",
    admin_profile_verification: "Email Verification",
    admin_profile_verified: "Verified",
    admin_profile_not_verified: "Not Verified",
    admin_profile_send_verification: "Send Verification Email",
    admin_profile_update_success: "Profile updated successfully!",
    admin_profile_error_reauth: "This action is sensitive and requires recent login. Please log out and log back in to update your email or password.",
    admin_profile_error_generic: "An error occurred. Please try again.",
    admin_profile_send_password_reset: "Send Password Reset Email",
    admin_profile_password_reset_sent: "Password reset email sent!",
    admin_profile_title: "Edit Profile",
    admin_profile_photo_url: "Photo URL",
    admin_profile_photo_upload: "Upload new photo",
    admin_profile_change_photo: "Click to change photo",
    //AdminExperience
    admin_work_experience: "Work Experience",
    admin_education: "Education",
    admin_create_new: "Create New",
    admin_edit_item: "Edit Item",
    admin_item_title: "Title",
    admin_item_title_placeholder: "e.g., Software Developer",
    admin_item_location: "Company / Institution",
    admin_item_location_placeholder: "e.g., Google / MIT",
    admin_item_date: "Date Range",
    admin_item_date_placeholder: "e.g., 2020 - 2024",
    admin_item_description: "Description",
    admin_item_description_placeholder: "What you did, achievements...",
    admin_save: "Save",
    admin_cancel: "Cancel",
    admin_delete: "Delete",
    admin_delete_confirm: "Are you sure you want to delete this item?",
    admin_loading: "Loading items...",
    admin_no_items: "No items available",
    admin_item_date_start: "Start Date",
    admin_item_date_start_placeholder: "e.g., 2020",
    admin_item_date_end: "End Date",
    admin_item_date_end_placeholder: "e.g., 2024 or Present",
    //AdminPorfolio
    admin_manage_portfolio: "Manage Portfolio",
    admin_create_project: "Create New Project",
    admin_edit_project: "Edit Project",
    admin_project_name: "Project Name",
    admin_project_desc: "Short Description",
    admin_project_tools: "Tools (separated by comma)",
    admin_project_tools_placeholder: "e.g., React, Firebase, CSS",
    admin_project_image_url: "Image URL (ImageHolder)",
    admin_project_storage_path: "Storage Path (imagePath)",
    admin_project_app_url: "App/Repo URL (URLApp)",
    admin_project_year: "Year",
    admin_project_visible: "Visible?",
    admin_project_image_url: "Image URL (ImageHolder)",
    admin_project_photo_upload: "Project Image",
    admin_project_change_photo: "Click to change image",
    //AdminContact
    admin_manage_contact: "Manage Contact Page",
    admin_contact_images: "Page Images",
    admin_contact_main_image: "Main Image (Desktop)",
    admin_contact_profile_image: "Profile Image (Mobile)",
    admin_contact_links: "Contact Links",
    admin_link_name: "Link Name",
    admin_link_infoname: "Info / Username",
    admin_link_url: "URL",
    admin_link_type: "Type",
    admin_link_type_personal: "Personal",
    admin_link_type_social: "Social",
    //NotFound
    notfound_title: "Lost in Space",
    notfound_description: "It seems you've wandered into an unknown sector of the galaxy. The page you're looking for doesn't exist or was moved to another dimension.",
    notfound_button: "Return to Base",
    // Footer
    footer_text: "Developed by Rafgui012",
    //Header
    back_text: "Back",
};
