/* eslint-disable no-irregular-whitespace */
export const es = {
    home_title: "Soy Rafael Angulo",
    home_subtitle: "Rafgui es mi marca personal y representa",
    portfolio: "Portafolio",
    experience: "Experiencia",
    contact: "Contacto",
    home: "Inicio",
    blog: "Blog",
    // Portfolio
    portfolio_title: "Portafolio",
    portfolio_description: "Bienvenido a mi portafolio, donde te invito a explorar la diversidad de proyectos y experiencias que han moldeado mi trayectoria profesional.",
    tools_label: "Herramientas y Tecnologías",
    // Experience
    experience_title: "Experiencia",
    work_text: "Trabajos",
    education_text: "Educación",
    // Contact
    contact_title: "Rafael Angulo Ealo",
    contact_description: "Puedes encontrarme en estas plataformas o enviarme un correo. ¡Hablemos!",
    //Blog
    blog_filtering_by: "Filtrando por",
    blog_filter_type_category: "categoría",
    blog_filter_type_year: "año",
    blog_filter_type_author: "autor",
    blog_clear: "Limpiar",
    blog_clear_filter: "Limpiar filtro",
    blog_no_posts_filter_prefix: "No hay posts que coincidan con el filtro",
    blog_no_posts_available: "No hay posts disponibles por el momento.",
    blog_show_all: "Mostrar todos los posts",
    //BlogSideBar
    blog_filter_posts: "Filtrar Posts",
    blog_categories: "Categorías",
    blog_years: "Años",
    blog_written_by: "Escrito por",
    blog_no_categories: "No hay categorías disponibles",
    blog_no_years: "No hay años disponibles",
    blog_no_authors: "No hay autores disponibles",
    // BlogPostPage
    blog_title: "Blog de Rafael",
    blog_post_not_found: "Post no encontrado.",
    blog_load_fail: "Error al cargar el post.",
    blog_oops_title: "Oops! Algo salió mal.",
    blog_back_to_blog: "Volver al Blog",
    blog_by: "Por",
    blog_my_opinion: "Mi Opinión",
    blog_opinion_not_available: "Opinión no disponible.",
    blog_no_opinion_yet: "Aún no hay opinión.",
    blog_comments: "Comentarios",
    blog_anonymous: "Anónimo",
    blog_be_first_comment: "Sé el primero en comentar.",
    blog_your_opinion: "Tu Opinión",
    blog_form_placeholder: "Escribe tu opinión aquí...",
    blog_submit_error: "Hubo un error al guardar tu opinión. Inténtalo de nuevo.",
    blog_rate_limit_error: "Debes esperar 30 minutos antes de enviar un nuevo comentario en este post.",
    blog_submit_saving: "Guardando...",
    blog_submit_save: "Guardar Opinión",
    //LoginPage
    login_title: "Iniciar Sesión",
    login_email: "Correo Electrónico",
    login_password: "Contraseña",
    login_btn: "Iniciar Sesión",
    login_forgot_password: "¿Olvidaste tu contraseña?",
    login_password_reset_sent: "¡Correo de reestablecimiento enviado! Revisa tu bandeja de entrada.",
    login_email_required_for_reset: "Por favor, ingresa tu email arriba.",
    login_password_reset_error: "Error al enviar el correo. Inténtalo de nuevo.",
    //AdminPanel
    admin_title: "Panel de Admin",
    admin_welcome: "Bienvenido",
    admin_logout: "Cerrar Sesión",
    admin_manage_blog: "Gestionar Blog",
    admin_manage_portfolio: "Gestionar Portafolio",
    admin_manage_experience: "Gestionar Experiencia",
    admin_back_to_dash: "Volver al Panel",
    //AdminBlog
    admin_manage_blog: "Gestionar Blog",
    admin_create_post: "Crear Nuevo Post",
    admin_edit_post: "Editar Post",
    admin_post_title: "Título del Post",
    admin_post_author: "Autor",
    admin_post_categories: "Categorías (separadas por coma)",
    admin_post_categories_placeholder: "Ej: Tech, Dev, AI",
    admin_post_image: "Imagen de Cabecera",
    admin_post_short_desc: "Descripción Corta (Vista Previa)",
    admin_post_content: "Contenido (Markdown)",
    admin_post_opinion: "Mi Opinión (Markdown)",
    admin_post_comments: "Gestionar Comentarios",
    admin_post_comments_enable: "Habilitar comentarios de visitantes",
    admin_post_no_comments: "Aún no hay comentarios en este post.",
    admin_post_delete_comment: "¿Eliminar este comentario?",
    //AdminProfile
    admin_profile_title: "Editar Perfil",
    admin_profile_wip: "Edición de perfil próximamente...",
    admin_profile_tooltip: "Editar Perfil",
    admin_logout_tooltip: "Cerrar Sesión",
    admin_profile_display_name: "Nombre de Usuario",
    admin_profile_photo_url: "URL de la Foto",
    admin_profile_update_profile: "Actualizar Perfil",
    admin_profile_email_address: "Dirección de Email",
    admin_profile_new_email: "Nuevo Email",
    admin_profile_update_email: "Actualizar Email",
    admin_profile_password: "Contraseña",
    admin_profile_new_password: "Nueva Contraseña",
    admin_profile_update_password: "Actualizar Contraseña",
    admin_profile_verification: "Verificación de Email",
    admin_profile_verified: "Verificado",
    admin_profile_not_verified: "No Verificado",
    admin_profile_send_verification: "Enviar Email de Verificación",
    admin_profile_update_success: "¡Perfil actualizado con éxito!",
    admin_profile_error_reauth: "Esta acción es sensible y requiere un inicio de sesión reciente. Por favor, cierra sesión y vuelve a iniciar sesión para actualizar tu email o contraseña.",
    admin_profile_error_generic: "Ocurrió un error. Por favor, inténtalo de nuevo.",
    admin_profile_send_password_reset: "Enviar Email de Reestablecimiento",
    admin_profile_password_reset_sent: "¡Email de reestablecimiento enviado!",
    admin_profile_photo_url: "URL de la Foto",
    admin_profile_photo_upload: "Subir nueva foto",
    admin_profile_change_photo: "Haz clic para cambiar la foto",
    //AdminExperience
    admin_work_experience: "Experiencia Laboral",
    admin_education: "Educación",
    admin_create_new: "Crear Nuevo",
    admin_edit_item: "Editar Ítem",
    admin_item_title: "Título",
    admin_item_title_placeholder: "Ej: Software Developer",
    admin_item_location: "Empresa / Institución",
    admin_item_location_placeholder: "Ej: Google / MIT",
    admin_item_date: "Rango de Fechas",
    admin_item_date_placeholder: "Ej: 2020 - 2024",
    admin_item_description: "Descripción",
    admin_item_description_placeholder: "Qué hiciste, logros...",
    admin_save: "Guardar",
    admin_cancel: "Cancelar",
    admin_delete: "Eliminar",
    admin_delete_confirm: "¿Estás seguro de que quieres eliminar este ítem?",
    admin_loading: "Cargando ítems...",
    admin_no_items: "No hay ítems disponibles",
    admin_item_date_start: "Fecha de Inicio",
    admin_item_date_start_placeholder: "Ej: 2020",
    admin_item_date_end: "Fecha de Fin",
    admin_item_date_end_placeholder: "Ej: 2024 o Presente",
    //AdminPorfolio
    admin_manage_portfolio: "Gestionar Portafolio",
    admin_create_project: "Crear Nuevo Proyecto",
    admin_edit_project: "Editar Proyecto",
    admin_project_name: "Nombre del Proyecto",
    admin_project_desc: "Descripción Corta",
    admin_project_tools: "Herramientas (separadas por coma)",
    admin_project_tools_placeholder: "Ej: React, Firebase, CSS",
    admin_project_image_url: "URL de Imagen (ImageHolder)",
    admin_project_storage_path: "Ruta de Storage (imagePath)",
    admin_project_app_url: "URL de la App/Repo (URLApp)",
    admin_project_year: "Año",
    admin_project_visible: "¿Visible?",
    admin_project_image_url: "URL de Imagen (ImageHolder)",
    admin_project_photo_upload: "Imagen del Proyecto",
    admin_project_change_photo: "Haz clic para cambiar la imagen",
    //AdminContact
    admin_manage_contact: "Gestionar Página de Contacto",
    admin_contact_images: "Imágenes de la Página",
    admin_contact_main_image: "Imagen Principal (Escritorio)",
    admin_contact_profile_image: "Imagen de Perfil (Móvil)",
    admin_contact_links: "Enlaces de Contacto",
    admin_link_name: "Nombre del Enlace",
    admin_link_infoname: "Info / Usuario",
    admin_link_url: "URL",
    admin_link_type: "Tipo",
    admin_link_type_personal: "Personal",
    admin_link_type_social: "Social",
    //NotFound
    notfound_title: "Perdido en el Espacio",
    notfound_description: "Parece que te has desviado a un sector desconocido de la galaxia. La página que buscas no existe o fue movida a otra dimensión.",
    notfound_button: "Volver a la base",
    // Footer
    footer_text: "Desarrollado por Rafgui012",
    //Header
    back_text: "Atras",
};
